# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(default='Site Name', max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
