# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_url',
            field=models.CharField(default='www.naturerichpropertieshonduras.com', max_length=255),
            preserve_default=False,
        ),
    ]
