# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20161111_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='about_en',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='address1_en',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='address2_en',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='sitename_en',
        ),
    ]
