# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20161111_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='address1_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='address2_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='sitename_en',
            field=models.CharField(default='Site Name', max_length=255, null=True),
        ),
    ]
