# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20161111_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('position', models.PositiveIntegerField(verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Menu Configuration',
            },
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_en',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_es',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='address1',
            field=models.CharField(max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='address1_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='address1_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='address2',
            field=models.CharField(max_length=255, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='address2_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='address2_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_url',
            field=models.CharField(max_length=255, verbose_name='Site URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='sitename',
            field=models.CharField(default='Site Name', max_length=255, verbose_name='Site name'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='sitename_en',
            field=models.CharField(default='Site Name', max_length=255, null=True, verbose_name='Site name'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='sitename_es',
            field=models.CharField(default='Site Name', max_length=255, null=True, verbose_name='Site name'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='telephone',
            field=models.CharField(max_length=255, verbose_name='Telephone'),
        ),
    ]
