# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_menuitem_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_profile', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('gplus', 'Google+')], default='facebook', max_length=20, unique=True)),
                ('url', models.URLField(verbose_name='Social Profile URL')),
            ],
            options={
                'verbose_name': 'Social Profile',
                'verbose_name_plural': 'Social Profiles',
            },
        ),
    ]
