# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20161112_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
