# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_socialprofile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='icon',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='social_profile',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('google-plus', 'Google+')], default='facebook', max_length=20, unique=True, verbose_name='Social Profile'),
        ),
    ]
