# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20161113_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialprofile',
            name='position',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Position'),
            preserve_default=False,
        ),
    ]
