# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_socialprofile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialprofile',
            name='icon',
        ),
    ]
