# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_socialprofile_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', stdimage.models.StdImageField(blank=True, upload_to='banner', verbose_name='Picture')),
                ('caption_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption Title')),
                ('caption_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption Description')),
            ],
            options={
                'verbose_name': 'Banner Item',
                'verbose_name_plural': 'Banner Items',
            },
        ),
    ]
