# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_introbanner_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='telephone2',
            field=models.CharField(default='+504 2440-1111', max_length=255, verbose_name='Landline'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='telephone',
            field=models.CharField(max_length=255, verbose_name='Mobile'),
        ),
    ]
