# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20161118_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('picture', stdimage.models.StdImageField(blank=True, upload_to='testimonials', verbose_name='Picture')),
                ('text', models.TextField(verbose_name='Testimonial text')),
                ('text_en', models.TextField(null=True, verbose_name='Testimonial text')),
                ('text_es', models.TextField(null=True, verbose_name='Testimonial text')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
