# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='url_en',
            field=models.CharField(max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='url_es',
            field=models.CharField(max_length=255, null=True, verbose_name='URL'),
        ),
    ]
