# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20161216_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_published', models.DateField()),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
