# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20170106_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
