# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20170106_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='intro',
            field=models.TextField(blank=True, null=True, verbose_name='Introduction'),
        ),
    ]
