# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_blogpost_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='intro_en',
            field=models.TextField(blank=True, null=True, verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='intro_es',
            field=models.TextField(blank=True, null=True, verbose_name='Introduction'),
        ),
    ]
