# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
