# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_auto_20161115_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', stdimage.models.StdImageField(blank=True, upload_to='properties/main', verbose_name='Picture')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.Property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Picture',
                'verbose_name_plural': 'Property Pictures',
            },
        ),
    ]
