# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_auto_20161119_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypicture',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='realestate.Property', verbose_name='Property'),
        ),
    ]
