# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_auto_20161119_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='picture',
        ),
    ]
