# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0013_property_map_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypicture',
            name='alt_text',
            field=models.TextField(default=None, verbose_name='Alternative Text'),
        ),
    ]
