# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0014_propertypicture_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypicture',
            name='alt_text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Alternative Text'),
        ),
    ]
