# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0016_auto_20161125_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertypicture',
            name='alt_text',
        ),
    ]
