# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0018_propertypicture_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertypicture',
            name='alt_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Alternative Text'),
        ),
        migrations.AddField(
            model_name='propertypicture',
            name='alt_text_es',
            field=models.TextField(blank=True, null=True, verbose_name='Alternative Text'),
        ),
    ]
