# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 20:04
from __future__ import unicode_literals

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0019_auto_20161125_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tags_field',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
