# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0020_property_tags_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='tags_field',
        ),
    ]
