# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0023_property_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(default='custom-slug', unique=True),
        ),
    ]
