# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0025_auto_20161216_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='slug',
        ),
    ]
